use axum::response::{IntoResponse, IntoResponseParts};

pub(crate) enum Either<L, R> {
    Left(L),
    Right(R),
}

impl<L, R> IntoResponseParts for Either<L, R>
where
    L: IntoResponseParts,
    R: IntoResponseParts,
{
    type Error = Either<L::Error, R::Error>;

    fn into_response_parts(
        self,
        res: axum::response::ResponseParts,
    ) -> Result<axum::response::ResponseParts, Self::Error> {
        match self {
            Either::Left(l) => l.into_response_parts(res).map_err(|e| Either::Left(e)),
            Either::Right(r) => r.into_response_parts(res).map_err(|e| Either::Right(e)),
        }
    }
}

impl<L, R> IntoResponse for Either<L, R>
where
    L: IntoResponse,
    R: IntoResponse,
{
    fn into_response(self) -> axum::response::Response {
        match self {
            Either::Left(l) => l.into_response(),
            Either::Right(r) => r.into_response(),
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::utils::opus_file_size;

    #[test]
    fn test_sparkle_opus_size() {
        // data generated by transcoding [220617][MVC-0064] Animelo Summer Live 2022 -Sparkle- テーマソング
        assert_eq!(opus_file_size(248745, 64, 60), 2006233);
        assert_eq!(opus_file_size(248745, 128, 60), 4004605);
        assert_eq!(opus_file_size(248745, 192, 60), 6002977);
        assert_eq!(opus_file_size(248745, 256, 60), 8001349);
    }

    #[test]
    fn test_sakuranotoki_opus_size() {
        assert_eq!(opus_file_size(80361372 * 1000 / 44100, 64, 20), 14719255);
    }
}
